=== shimpeif/carSim/trick_source/data_products/DPX/XML/DTD/Product.dtd
<!-- Trick DP Product definition -->
<!-- V 1.0 -->
<!ELEMENT fname       (#PCDATA)>
<!ELEMENT title       (#PCDATA)>
<!ELEMENT tstart      (#PCDATA)>
<!ELEMENT tstop       (#PCDATA)>
<!ELEMENT frequency   (#PCDATA)>
<!ELEMENT label       (#PCDATA)>
<!ELEMENT units       (#PCDATA)>
<!ELEMENT measurement (var, units)>
<!ELEMENT var         (#PCDATA)>

<!-- A varcase construct is used to indicate that two or variable names mean the same thing.
     If the data for a curve can't be found for the first name, try the second and so forth.
-->
<!ELEMENT varcase     (var, var, var?)>
<!ELEMENT xaxis       (label?, units?)>
<!ELEMENT yaxis       (label?, units?)>
<!ELEMENT zaxis       (label?, units?)>
<!ELEMENT column      (label?, units?, var)>
<!ELEMENT curve       ((var, var, var?)|varcase+)>
<!ELEMENT table       (title?, tstart?, tstop?, frequency?, column+)>
<!ELEMENT plot        (title?, tstart?, tstop?, frequency?, (xaxis|yaxis|zaxis)*, curve+)>
<!ELEMENT page        (title?, tstart?, tstop?, frequency?, plot+)>
<!ELEMENT inputs      (var+)>
<!ELEMENT outputs     (measurement+)>
<!ELEMENT extfn       (fname, inputs, outputs)>
<!ELEMENT product     (title?, tstart?, tstop?, frequency?, extfn*, (page|table)+)>

<!ATTLIST product version                 CDATA #REQUIRED>
<!ATTLIST product foreground_color        CDATA #IMPLIED>
<!ATTLIST product background_color        CDATA #IMPLIED>

<!ATTLIST page foreground_color           CDATA #IMPLIED>
<!ATTLIST page background_color           CDATA #IMPLIED>
<!ATTLIST page hcells                     CDATA #IMPLIED>
<!ATTLIST page vcells                     CDATA #IMPLIED>

<!ATTLIST page presentation               CDATA #IMPLIED>
<!ATTLIST page gnuplot_template           CDATA #IMPLIED>
<!ATTLIST page gnuplot_object             CDATA #IMPLIED>
<!ATTLIST page gnuplot_geom               CDATA #IMPLIED>
<!ATTLIST page gnuplot_plot_ratio         CDATA #IMPLIED>
<!ATTLIST page gnuplot_page_orientation   CDATA #IMPLIED>

<!ATTLIST table foreground_color          CDATA #IMPLIED>
<!ATTLIST table background_color          CDATA #IMPLIED>

<!ATTLIST plot x_scale                    CDATA #IMPLIED>
<!ATTLIST plot xmin                       CDATA #IMPLIED>
<!ATTLIST plot xmax                       CDATA #IMPLIED>
<!ATTLIST plot y_scale                    CDATA #IMPLIED>
<!ATTLIST plot ymin                       CDATA #IMPLIED>
<!ATTLIST plot ymax                       CDATA #IMPLIED>
<!ATTLIST plot grid                       CDATA #IMPLIED>
<!ATTLIST plot grid_color                 CDATA #IMPLIED>
<!ATTLIST plot foreground_color           CDATA #IMPLIED>
<!ATTLIST plot background_color           CDATA #IMPLIED>
<!ATTLIST plot font                       CDATA #IMPLIED>

<!-- The format attribute specifies the printf() format string to    -->
<!-- be used for printing y variable data. (e.g., "%18.6e")              -->
<!ATTLIST yaxis format                    CDATA #IMPLIED>

<!-- The format attribute specifies the printf() format string to    -->
<!-- be used for printing column data. (e.g., "%18.6e")              -->
<!ATTLIST column format                   CDATA #IMPLIED>

<!-- =============================================================== -->
<!-- <var> ATTRIBUTES                                                -->
<!-- =============================================================== -->
<!ATTLIST var label                       CDATA #IMPLIED>

<!-- <var>'s from_units attribute specifies the units to be assumed  -->
<!-- for the recorded data if and only if the recorded data doesn't  -->
<!-- contain units information for it's variables. -->
<!-- This attribute is used for data streams that don't supply       -->
<!-- actual units. For streams that supply actual units (like .trk   -->
<!-- files) this attribute is ignored. -->
<!ATTLIST var from_units                  CDATA #IMPLIED>

<!-- <var>'s units attribute indicates the units that recorded data -->
<!-- should be converted to, below being displayed.                 -->
<!ATTLIST var units                       CDATA #IMPLIED>

<!ATTLIST var bias                        CDATA #IMPLIED>
<!ATTLIST var scale                       CDATA #IMPLIED>
<!ATTLIST var max                         CDATA #IMPLIED>
<!ATTLIST var symbol_style                CDATA #IMPLIED>
<!ATTLIST var symbol_size                 CDATA #IMPLIED>
<!ATTLIST var line_style                  CDATA #IMPLIED>
<!ATTLIST var line_color                  CDATA #IMPLIED>
<!ATTLIST var gnuplot_line_style          CDATA #IMPLIED>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/test/TEST_DATA/product_9.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "../../XML/DTD/Product.dtd">

<!-- Description: multiple plots, no attributes -->

<product version="1.0">
   <page vcells="3">
      <title>Page of Squiggles</title>
      <plot>
         <title>Squiggle 1</title>
         <curve>
            <var>sys.exec.out.time</var>
            <var>sun_predictor.sun.JD</var>
         </curve>
      </plot>
      <plot>
        <title>Squiggle 2</title> 
		<curve>
            <var>sys.exec.out.time</var>
            <var>sun_predictor.sun.declination</var>
         </curve>
      </plot>
      <plot>
        <title>Squiggle 3</title> 
		<curve>
            <var>sys.exec.out.time</var>
            <var>sun_predictor.sun.hour_angle</var>
         </curve>
      </plot>
   </page>
</product>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/product_testview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "../../XML/DTD/Product.dtd">
<product version="1.0" foreground_color="#ffffff" background_color="#885588"> 
	<page foreground_color="#ffffff" 
		  background_color="#885588" 
		  hcells="1" vcells="2"
		  presentation="SIMPLE"
		  gnuplot_template="this one"
		  gnuplot_object="ball"
		  gnuplot_geom="square"
		  gnuplot_plot_ratio="1.5"
		  gnuplot_page_orientation="landscape">
		<title>This is a page</title>
		<tstart>5</tstart>
		<tstop>900</tstop>
		<frequency>2.0</frequency>
		<plot x_scale="1.0" xmin="-100000" xmax="100000"
			  y_scale="2.0" ymin="-200000" ymax="200000"
			  grid="yes"  grid_color="pink"
			  foreground_color="#ffffff" background_color="#000000"
			  font="helvetica">
			<title>This is a page</title>
			<tstart>8</tstart>
			<tstop>850</tstop>
			<frequency>5.0</frequency>
			<xaxis>
				<label>Mass</label>
		    	<units>g</units>
			</xaxis>
			<yaxis>
		    	<label>Density</label>
		    	<units>K</units>
			</yaxis>
			<curve>
				<var label="Variable X"
					 from_units="s" 		  units="min"
					 bias="left?" 	scale="4" max="100000000"
					 symbol_style="circles"   symbol_size="small"
					 line_style="dotted" 	  line_color="green"
					 gnuplot_line_style="box">sun_predictor.sun.observer_offset_from_UTC</var>
				<var>sun_predictor.sun.observer_latitude</var>
			</curve>
		</plot>
	</page>
	<table foreground_color="#ffffff" 
		   background_color="#000000">
		<title>This is a table</title>
		<tstart>10</tstart>
		<tstop>200</tstop>
		<frequency>70.0</frequency>
		<column format="feng shui">
			<label>Time</label>
			<units>kg</units>
			<var label="Variable 1"
			     from_units="day"      units="s"
			     bias="italics"   scale="4" max="100000000"
			     symbol_style="asterisk"   symbol_size="large"
			     line_style="thick"      line_color="blue"
			     gnuplot_line_style="thick">sys.exec.out.time</var>
		</column>
		<column format="normal">
			<label>Pressure</label>
		    <units>ft</units>
		    <var label="Variable 2"
		         from_units="revolution"           units="arcsecond"
		         bias="left?"   scale="4" max="34579257"
		         symbol_style="dot"   symbol_size="huge"
		         line_style="shiny"      line_color="yellow"
		         gnuplot_line_style="normal">sun_predictor.sun.hour_angle</var>
		</column>
	</table>
</product>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/product_4.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "../../XML/DTD/Product.dtd">

<!-- Description: Plot of Y(t) vs. t, with attributes, titles, labels, units -->

<product version="1.0">
   <title>Solar Elevation</title>
   <page>
      <title>Solar Elevation for a Day</title>
      <plot grid="yes"
            grid_color="blue"
            font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
            background_color="#eef0ff">
         <title>Sun Elevation vs. Time</title>
         <xaxis>
            <label>Time</label>
            <units>hr</units>
         </xaxis>
         <yaxis>
            <label>Elevation</label>
            <units>d</units>
         </yaxis>
         <curve>  
            <var>sys.exec.out.time</var>
            <var line_color="red" line_style="dash">sun_predictor.sun.solar_elevation</var>
         </curve>  
      </plot>
   </page>
</product>

=== shimpeif/carSim/trick_source/data_products/DPX/TESTING/TEST_DATA/product_7.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">

<!-- Description: Page with multiple plots -->

<product version="1.0">
   <title>title of the product</title>
   <page vcells="3">
      <title>Solar Elevation for a Day</title>
      <plot grid="yes"
            font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
            background_color="#fff0ff">
         <title>Sun Elevation vs. Time</title>
         <xaxis>
            <label>Time</label>
            <units>hr</units>
         </xaxis>
         <yaxis>
            <label>Elevation</label>
            <units>d</units>
         </yaxis>
         <curve>
            <var>sys.exec.out.time</var>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </curve>
      </plot>
      <plot grid="yes"
            font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
            background_color="#f0fff0">
         <title>Sun Azimuth vs. Time</title>
         <xaxis format="%g">
            <label>Time</label>
            <units>hr</units>
         </xaxis>
         <yaxis>
            <label>Azimuth</label>
            <units>d</units>
         </yaxis>
         <curve>
            <var>sys.exec.out.time</var>
            <var line_color = "#323200">sun_predictor.sun.solar_azimuth</var>
         </curve>
      </plot>
      <plot grid="yes"
            font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
            background_color="#fffff0">
         <title>Sun Elevation vs. Azimuth</title>
         <xaxis format="%g">
            <label>Azimuth</label>
            <units>d</units>
         </xaxis>
         <yaxis>
            <label>Elevation</label>
            <units>d</units>
         </yaxis>
         <curve>
            <var>sun_predictor.sun.solar_azimuth</var>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </curve>
      </plot>
   </page>
</product>

=== shimpeif/carSim/trick_sims/SIM_sun/DP_Product/DP_Solar_AZ_EL.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product background_color="#e6e6e6" foreground_color="#000000" version="1.0">
    <tstart>-1.0E20</tstart>
    <tstop>1.0E20</tstop>
    <frequency>0.0</frequency>
    <page background_color="#e6e6e6" foreground_color="#000000" hcells="0" vcells="0">
        <title>Page</title>
        <plot background_color="#f0f0ff" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Sun Elevation vs. Time</title>
            <xaxis>
                <label>Time</label>
            </xaxis>
            <yaxis>
                <label>Elevation</label>
            </yaxis>
            <curve>
                <var units="hr">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" line_color="#323200" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="degree">sun_predictor.sun.solar_elevation</var>
            </curve>
        </plot>
    </page>
    <page background_color="#e6e6e6" foreground_color="#000000" hcells="0" vcells="0">
        <title>Page</title>
        <plot background_color="#fffff0" foreground_color="#000000" grid="Yes" grid_color="azure3">
            <title>Plot</title>
            <curve>
                <var units="degree">sun_predictor.sun.solar_azimuth</var>
                <var gnuplot_line_style="lines" line_color="brown" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="degree">sun_predictor.sun.solar_elevation</var>
            </curve>
        </plot>
    </page>
    <page background_color="#e6e6e6" foreground_color="#000000" hcells="0" vcells="0">
        <title>Page</title>
        <plot background_color="#f0fff0" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Sun Azimuth vs. Time</title>
            <xaxis>
                <label>Time</label>
            </xaxis>
            <yaxis>
                <label>Azimuth</label>
            </yaxis>
            <curve>
                <var units="hr">sys.exec.out.time</var>
                <var units="degree">sun_predictor.sun.solar_azimuth</var>
            </curve>
        </plot>
    </page>
</product>

=== shimpeif/carSim/trick/test/SIM_test_dp/DP_Product/DP_test.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product background_color="#e6e6e6" foreground_color="#000000" version="1.0">
    <tstart>-1.0E20</tstart>
    <tstop>1.0E20</tstop>
    <frequency>0.0</frequency>
    <page background_color="#e6e6e6" foreground_color="#000000" hcells="0" vcells="0">
        <title>Plot Test</title>
        <plot background_color="#e6e6e6" foreground_color="#000000" grid="No" grid_color="#ffffff">
            <title>Doubles</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Double-1" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[0]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Double-2" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[1]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Double-3" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[2]</var>
            </curve>
        </plot>
        <plot background_color="#e6e6e6" foreground_color="#000000" grid="No" grid_color="#ffffff">
            <title>Floats</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Float-1" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].f[0]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Float-2" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].f[1]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Float-3" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].f[2]</var>
            </curve>
        </plot>
        <plot background_color="#e6e6e6" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ints</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Int-1" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m">dpx.test.s3[1].s2[1][1].s1[1][1].i[0]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Int-2" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m">dpx.test.s3[1].s2[1][1].s1[1][1].i[1]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Int-3" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m">dpx.test.s3[1].s2[1][1].s1[1][1].i[2]</var>
            </curve>
        </plot>
        <plot background_color="#e6e6e6" foreground_color="#000000" grid="No" grid_color="#ffffff">
            <title>Elvis Test</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="One for the money" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="kg*m/s2">dpx.test.s3[1].s2[0][0].s1[0][0].d[0]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Two for the show" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[0][0].d[1]</var>
            </curve>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Three to get ready" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="kg*m/s2">dpx.test.s3[1].s2[2][1].s1[1][1].d[2]</var>
            </curve>
        </plot>
    </page>
    <table>
        <title>Table</title>
        <column>
            <units>--</units>
            <var units="s">sys.exec.out.time</var>
        </column>
        <column>
            <label>Double-1</label>
            <units>--</units>
            <var label="Double-1" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[0]</var>
        </column>
        <column>
            <label>Double-2</label>
            <units>--</units>
            <var label="Double-2" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[1]</var>
        </column>
        <column>
            <label>Double-3</label>
            <units>--</units>
            <var label="Double-3" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[2]</var>
        </column>
        <column>
            <label>Float-1</label>
            <units>--</units>
            <var label="Float-1" units="m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].f[0]</var>
        </column>
        <column>
            <label>Float-2</label>
            <units>--</units>
            <var label="Float-2" units="m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].f[1]</var>
        </column>
        <column>
            <label>Float-3</label>
            <units>--</units>
            <var label="Float-3" units="m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].f[2]</var>
        </column>
        <column>
            <label>Int-1</label>
            <units>--</units>
            <var label="Int-1" units="m">dpx.test.s3[1].s2[1][1].s1[1][1].i[0]</var>
        </column>
        <column>
            <label>Int-2</label>
            <units>--</units>
            <var label="Int-2" units="m">dpx.test.s3[1].s2[1][1].s1[1][1].i[1]</var>
        </column>
        <column>
            <label>Int-3</label>
            <units>--</units>
            <var label="Int-3" units="m">dpx.test.s3[1].s2[1][1].s1[1][1].i[2]</var>
        </column>
        <column>
            <label>Value 1</label>
            <units>--</units>
            <var label="Value 1" units="kg*m/s2">dpx.test.s3[0].s2[0][0].s1[0][0].d[0]</var>
        </column>
        <column>
            <label>Value 2</label>
            <units>--</units>
            <var label="Value 2" units="kg*m/s2">dpx.test.s3[0].s2[0][1].s1[0][2].d[1]</var>
        </column>
        <column>
            <label>Value 3</label>
            <units>--</units>
            <var label="Value 3" units="kg*m/s2">dpx.test.s3[0].s2[1][1].s1[0][0].d[2]</var>
        </column>
        <column>
            <label>Value 1</label>
            <units>--</units>
            <var label="Value 1" units="kg*m/s2">dpx.test.s3[1].s2[0][0].s1[0][0].d[0]</var>
        </column>
        <column>
            <label>Value 2</label>
            <units>--</units>
            <var label="Value 2" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[0][0].d[1]</var>
        </column>
        <column>
            <label>Value 3</label>
            <units>--</units>
            <var label="Value 3" units="kg*m/s2">dpx.test.s3[1].s2[1][1].s1[1][1].d[2]</var>
        </column>
    </table>
</product>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/TESTING/TEST_DATA/product_3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">

<!-- Description: Table, no attributes, titles -->

<product version="1.0">
      <table>
         <column>
            <var>sys.exec.out.time</var>
         </column>
         <column>
            <var>sun_predictor.sun.solar_azimuth</var>
         </column>
         <column>
            <var>sun_predictor.sun.solar_elevation</var>
         </column>
      </table>
</product>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/product_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "../../XML/DTD/Product.dtd">
<product version="1.0" background_color="#885588">

<!-- Description: Multiple Tables and multiple pages with plots -->

      <table>
         <title>My Two Column Table</title>
         <column format="%24.10f">
            <label>Time</label>
            <var>sys.exec.out.time</var>
         </column>
         <column format="%16.5q">
            <label>Azimuth</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_azimuth</var>
         </column>
         <column format="%16.5f">
            <label>Elevation</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
      </table>
      <page>
         <title>Solar Elevation for a Day</title>
         <plot grid="yes"
               font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*">
            <title>Sun Elevation vs. Time</title>
            <xaxis>
               <label>Time</label>
               <units>hr</units>
            </xaxis>
            <yaxis>
               <label>Elevation</label>
               <units>d</units>
            </yaxis>
            <curve>
               <var>sys.exec.out.time</var>
               <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
            </curve>
         </plot>
      </page>
      <page>
         <plot grid="yes"
               font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
               background_color="#fffff0">
            <title>Sun Elevation vs. Azimuth</title>
            <xaxis>
               <label>Azimuth</label>
               <units>d</units>
            </xaxis>
            <yaxis>
               <label>Elevation</label>
               <units>d</units>
            </yaxis>
            <curve>
               <var>sun_predictor.sun.solar_azimuth</var>
               <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
            </curve>
         </plot>
      </page>

      <table background_color="#ffeebb">
         <title>Four Column Table</title>
         <column format="%24.10f">
            <units>s</units>
            <var>sys.exec.out.time</var>
         </column>
         <column format="%16.5f">
            <label>Seconds</label>
            <var line_color = "#323200">sun_predictor.sun.local_time.sec</var>
         </column>
         <column format="%16.5f">
            <label>Day</label>
            <var line_color = "#323200">sun_predictor.sun.local_time.day</var>
         </column>
         <column format="%16.5f">
         	<label>Month</label>
            <var line_color = "#323200">sun_predictor.sun.local_time.month</var>
         </column>
         <column format="%16.5f">
         	<label>Year</label>
            <var line_color = "#323200">sun_predictor.sun.local_time.year</var>
         </column>
      </table>

</product>
