=== shimpeif/carSim/trick_source/data_products/DPX/XML/DTD/Product.dtd
<!-- Trick DP Product definition -->
<!-- V 1.0 -->
<!ELEMENT fname       (#PCDATA)>
<!ELEMENT title       (#PCDATA)>
<!ELEMENT tstart      (#PCDATA)>
<!ELEMENT tstop       (#PCDATA)>
<!ELEMENT frequency   (#PCDATA)>
<!ELEMENT label       (#PCDATA)>
<!ELEMENT units       (#PCDATA)>
<!ELEMENT measurement (var, units)>
<!ELEMENT var         (#PCDATA)>

<!-- A varcase construct is used to indicate that two or variable names mean the same thing.
     If the data for a curve can't be found for the first name, try the second and so forth.
-->
<!ELEMENT varcase     (var, var, var?)>
<!ELEMENT xaxis       (label?, units?)>
<!ELEMENT yaxis       (label?, units?)>
<!ELEMENT zaxis       (label?, units?)>
<!ELEMENT column      (label?, units?, var)>
<!ELEMENT curve       ((var, var, var?)|varcase+)>
<!ELEMENT table       (title?, tstart?, tstop?, frequency?, column+)>
<!ELEMENT plot        (title?, tstart?, tstop?, frequency?, (xaxis|yaxis|zaxis)*, curve+)>
<!ELEMENT page        (title?, tstart?, tstop?, frequency?, plot+)>
<!ELEMENT inputs      (var+)>
<!ELEMENT outputs     (measurement+)>
<!ELEMENT extfn       (fname, inputs, outputs)>
<!ELEMENT product     (title?, tstart?, tstop?, frequency?, extfn*, (page|table)+)>

<!ATTLIST product version                 CDATA #REQUIRED>
<!ATTLIST product foreground_color        CDATA #IMPLIED>
<!ATTLIST product background_color        CDATA #IMPLIED>

<!ATTLIST page foreground_color           CDATA #IMPLIED>
<!ATTLIST page background_color           CDATA #IMPLIED>
<!ATTLIST page hcells                     CDATA #IMPLIED>
<!ATTLIST page vcells                     CDATA #IMPLIED>

<!ATTLIST page presentation               CDATA #IMPLIED>
<!ATTLIST page gnuplot_template           CDATA #IMPLIED>
<!ATTLIST page gnuplot_object             CDATA #IMPLIED>
<!ATTLIST page gnuplot_geom               CDATA #IMPLIED>
<!ATTLIST page gnuplot_plot_ratio         CDATA #IMPLIED>
<!ATTLIST page gnuplot_page_orientation   CDATA #IMPLIED>

<!ATTLIST table foreground_color          CDATA #IMPLIED>
<!ATTLIST table background_color          CDATA #IMPLIED>

<!ATTLIST plot x_scale                    CDATA #IMPLIED>
<!ATTLIST plot xmin                       CDATA #IMPLIED>
<!ATTLIST plot xmax                       CDATA #IMPLIED>
<!ATTLIST plot y_scale                    CDATA #IMPLIED>
<!ATTLIST plot ymin                       CDATA #IMPLIED>
<!ATTLIST plot ymax                       CDATA #IMPLIED>
<!ATTLIST plot grid                       CDATA #IMPLIED>
<!ATTLIST plot grid_color                 CDATA #IMPLIED>
<!ATTLIST plot foreground_color           CDATA #IMPLIED>
<!ATTLIST plot background_color           CDATA #IMPLIED>
<!ATTLIST plot font                       CDATA #IMPLIED>

<!-- The format attribute specifies the printf() format string to    -->
<!-- be used for printing y variable data. (e.g., "%18.6e")              -->
<!ATTLIST yaxis format                    CDATA #IMPLIED>

<!-- The format attribute specifies the printf() format string to    -->
<!-- be used for printing column data. (e.g., "%18.6e")              -->
<!ATTLIST column format                   CDATA #IMPLIED>

<!-- =============================================================== -->
<!-- <var> ATTRIBUTES                                                -->
<!-- =============================================================== -->
<!ATTLIST var label                       CDATA #IMPLIED>

<!-- <var>'s from_units attribute specifies the units to be assumed  -->
<!-- for the recorded data if and only if the recorded data doesn't  -->
<!-- contain units information for it's variables. -->
<!-- This attribute is used for data streams that don't supply       -->
<!-- actual units. For streams that supply actual units (like .trk   -->
<!-- files) this attribute is ignored. -->
<!ATTLIST var from_units                  CDATA #IMPLIED>

<!-- <var>'s units attribute indicates the units that recorded data -->
<!-- should be converted to, below being displayed.                 -->
<!ATTLIST var units                       CDATA #IMPLIED>

<!ATTLIST var bias                        CDATA #IMPLIED>
<!ATTLIST var scale                       CDATA #IMPLIED>
<!ATTLIST var max                         CDATA #IMPLIED>
<!ATTLIST var symbol_style                CDATA #IMPLIED>
<!ATTLIST var symbol_size                 CDATA #IMPLIED>
<!ATTLIST var line_style                  CDATA #IMPLIED>
<!ATTLIST var line_color                  CDATA #IMPLIED>
<!ATTLIST var gnuplot_line_style          CDATA #IMPLIED>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/product_5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "../../XML/DTD/Product.dtd">

<!-- Description: Plot of Z(t) vs. Y(t) vs. X(t), with attributes, titles, labels, units -->

<product version="1.0"
		 foreground_color="#000000"
		 background_color="#ffffff">
   <title>title of the product</title>
   <page>
      <title>Solar Elevation for a Day</title>
      <plot grid="yes"
            font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
            background_color="#fffff0">
         <title>Sun Time vs. Elevation vs. Azimuth</title>
         <xaxis>
            <label>Azimuth</label>
            <units>d</units>
         </xaxis>
         <yaxis format="%g">
            <label>Elevation</label>
            <units>d</units>
         </yaxis>
         <zaxis>
            <label>Time</label>
            <units>s</units>
         </zaxis>
         <curve>
            <var>sun_predictor.sun.solar_azimuth</var>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
            <var>sys.exec.out.time</var>
         </curve>
      </plot>
   </page>
</product>

=== shimpeif/carSim/trick/trick_sims/Ball/SIM_ball_L2/DP_Product/DP_x_position.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product background_color="#ede9e3" foreground_color="#000000" version="1.0">
    <tstart>-1.0E20</tstart>
    <tstop>1.0E20</tstop>
    <frequency>0.0</frequency>
    <page background_color="#ede9e3" foreground_color="#000000" hcells="0" vcells="0">
        <title>Page</title>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Plot</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var units="m">ball.state.out.position[0]</var>
            </curve>
        </plot>
    </page>
    <table>
        <title>Table</title>
        <column>
            <units>--</units>
            <var units="s">sys.exec.out.time</var>
        </column>
        <column>
            <units>--</units>
            <var units="m">ball.state.out.position[0]</var>
        </column>
    </table>
</product>

=== shimpeif/carSim/trick_source/data_products/DPX/TESTING/TEST_DATA/product_8.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product version="1.0" background_color="#885588">

<!-- Description: Multiple Tables and multiple pages with plots -->

      <table>
         <title>My Two Column Table</title>
         <column format="%24.10f">
            <label>Time</label>
            <var>sys.exec.out.time</var>
         </column>
         <column format="%16.5q">
            <label>Azimuth</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_azimuth</var>
         </column>
         <column format="%16.5f">
            <label>Elevation</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
      </table>
      <page>
         <title>Solar Elevation for a Day</title>
         <plot grid="yes"
               font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*">
            <title>Sun Elevation vs. Time</title>
            <xaxis>
               <label>Time</label>
               <units>hr</units>
            </xaxis>
            <yaxis>
               <label>Elevation</label>
               <units>d</units>
            </yaxis>
            <curve>
               <var>sys.exec.out.time</var>
               <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
            </curve>
         </plot>
      </page>
      <page>
         <plot grid="yes"
               background_color="#f0fff0">
            <title>Sun Azimuth vs. Time</title>
            <xaxis>
               <label>Time</label>
               <units>hr</units>
            </xaxis>
            <yaxis>
               <label>Azimuth</label>
               <units>d</units>
            </yaxis>
            <curve>
               <var>sys.exec.out.time</var>
               <var line_color = "#323200">sun_predictor.sun.solar_azimuth</var>
            </curve>
         </plot>
      </page>
      <page>
         <plot grid="yes"
               font="-*-new century schoolbook-bold-r-*--12-*-*-*-*-*-*-*"
               background_color="#fffff0">
            <title>Sun Elevation vs. Azimuth</title>
            <xaxis>
               <label>Azimuth</label>
               <units>d</units>
            </xaxis>
            <yaxis>
               <label>Elevation</label>
               <units>d</units>
            </yaxis>
            <curve>
               <var>sun_predictor.sun.solar_azimuth</var>
               <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
            </curve>
         </plot>
      </page>

      <table background_color="#ffeebb">
         <title>Six Column Table</title>
         <column format="%24.10f">
            <units>s</units>
            <var>sys.exec.out.time</var>
         </column>
         <column format="%16.5q">
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_azimuth</var>
         </column>
         <column format="%16.5f">
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
         <column format="%16.5f">
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
         <column format="%16.5f">
            <label>Elevation</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
         <column format="%16.5f">
            <label>Elevation</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
         <column format="%16.5f">
            <label>Elevation</label>
            <units>d</units>
            <var line_color = "#323200">sun_predictor.sun.solar_elevation</var>
         </column>
      </table>

</product>

=== shimpeif/carSim/trick_sims/Ball/SIM_ball_L2/DP_Product/DP_ball_states.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product background_color="#ede9e3" foreground_color="#000000" version="1.0">
    <tstart>-1.0E20</tstart>
    <tstop>1.0E20</tstop>
    <frequency>0.0</frequency>
    <page background_color="#ede9e3" foreground_color="#000000" hcells="0" vcells="0">
        <title>Ball X,Y Position, Velocity, and Acceleration States</title>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ball Acceleration States</title>
            <xaxis>
                <label>Time</label>
            </xaxis>
            <yaxis>
                <label>Accel</label>
            </yaxis>
            <curve>
                <var label="Time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="X Pos" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m">ball.state.out.position[0]</var>
            </curve>
            <curve>
                <var label="Time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Y Pos" line_color="#000000" line_style="Med_Fine_Dash" symbol_size="Tiny" symbol_style="None" units="m">ball.state.out.position[1]</var>
            </curve>
        </plot>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ball Velocity States</title>
            <xaxis>
                <label>Time</label>
            </xaxis>
            <yaxis>
                <label>Velocity</label>
            </yaxis>
            <curve>
                <var label="Time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="X Vel" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s">ball.state.out.velocity[0]</var>
            </curve>
            <curve>
                <var label="Time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Y Vel" line_color="#000000" line_style="Med_Fine_Dash" symbol_size="Tiny" symbol_style="None" units="m/s">ball.state.out.velocity[1]</var>
            </curve>
        </plot>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ball Acceleration States</title>
            <xaxis>
                <label>Time</label>
            </xaxis>
            <yaxis>
                <label>Accel</label>
            </yaxis>
            <curve>
                <var label="Time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="X Acc" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s2">ball.state.out.acceleration[0]</var>
            </curve>
            <curve>
                <var label="Time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="Y Acc" line_color="#000000" line_style="Med_Fine_Dash" symbol_size="Tiny" symbol_style="None" units="m/s2">ball.state.out.acceleration[1]</var>
            </curve>
        </plot>
    </page>
    <page background_color="#ede9e3" foreground_color="#000000" hcells="0" vcells="0">
        <title>Ball X,Y Cross Plots</title>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ball Y vs X Position</title>
            <xaxis>
                <label>X Pos</label>
            </xaxis>
            <yaxis>
                <label>Y Pos</label>
            </yaxis>
            <curve>
                <var label="X Pos" units="m">ball.state.out.position[0]</var>
                <var gnuplot_line_style="lines" label="Y Pos" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m">ball.state.out.position[1]</var>
            </curve>
        </plot>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ball Y vs X Velocity</title>
            <xaxis>
                <label>X Vel</label>
            </xaxis>
            <yaxis>
                <label>Y Vel</label>
            </yaxis>
            <curve>
                <var label="X Vel" units="m/s">ball.state.out.velocity[0]</var>
                <var gnuplot_line_style="lines" label="Y Vel" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s">ball.state.out.velocity[1]</var>
            </curve>
        </plot>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Ball Y vs X Acceleration</title>
            <xaxis>
                <label>X Accel</label>
            </xaxis>
            <yaxis>
                <label>Y Accel</label>
            </yaxis>
            <curve>
                <var units="m/s2">ball.state.out.acceleration[0]</var>
                <var gnuplot_line_style="lines" label="Y Acc" line_color="#000000" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m/s2">ball.state.out.acceleration[1]</var>
            </curve>
        </plot>
    </page>
</product>

=== shimpeif/carSim/trick_sims/Ball/SIM_ball_L1/DP_Product/DP_ball_states.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product background_color="#ede9e3" foreground_color="#000000" version="1.0">
    <title>Page</title>
    <tstart>-1.0E20</tstart>
    <tstop>1.0E20</tstop>
    <frequency>0.0</frequency>
    <page background_color="#ede9e3" foreground_color="#000000" hcells="0" vcells="0">
        <title>Ball X,Y Position, Velocity and Acceleration States</title>
        <plot background_color="#ede9e3" foreground_color="#000000" grid="Yes" grid_color="#ffffff">
            <title>Plot Position</title>
            <xaxis>
                <label>time</label>
            </xaxis>
            <yaxis>
                <label>Position</label>
            </yaxis>
            <curve>
                <var label="time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="position" line_color="#0000ff" line_style="Plain" symbol_size="Tiny" symbol_style="None" units="m">ball.state.output.position[0]</var>
            </curve>
            <curve>
                <var label="time" units="s">sys.exec.out.time</var>
                <var gnuplot_line_style="lines" label="index" line_color="#ff0000" line_style="Med_Fine_Dash" symbol_size="Tiny" symbol_style="None" units="m">ball.state.output.position[1]</var>
            </curve>
        </plot>
    </page>
</product>

=== shimpeif/carSim/trick/trick_sims/Ball/SIM_ball_L1/DP_Product/DP_ball_state_cmp.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">
<product background_color="" foreground_color="" version="1.0">
    <tstart>0.0</tstart>
    <tstop>0.0</tstop>
    <frequency>0.0</frequency>
    <page>
        <title>Page</title>
        <tstart>-1.0E20</tstart>
        <tstop>1.0E20</tstop>
        <frequency>0.0</frequency>
        <plot background_color="" font="" foreground_color="" grid="Off" grid_color="">
            <title>Plot</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var units="m" line_color="blue">ball.state.output.position[0]</var>
            </curve>
        </plot>
        <plot background_color="" font="" foreground_color="" grid="Off" grid_color="">
            <title>Plot</title>
            <curve>
                <var units="s">sys.exec.out.time</var>
                <var units="m" line_color="red">ball.state.output.position[1]</var>
            </curve>
        </plot>
    </page>
</product>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/TESTING/TEST_DATA/product_9.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "Product.dtd">

<!-- Description: Page with multiple plots for many runs demo. -->

<product version="1.0">
   <page vcells="3" >
      <title>Page of Squiggles</title>
      <plot background_color="#bbbbff">
         <title>Pitch</title>
         <curve>
            <var>sys.exec.out.time</var>
            <var>pitch</var>
         </curve>
      </plot>
      <plot background_color="#bbffbb">
         <curve>
            <var>sys.exec.out.time</var>
            <var>roll</var>
         </curve>
      </plot>
      <plot background_color="#ffbbbb">
         <curve>
            <var>sys.exec.out.time</var>
            <var>yaw</var>
         </curve>
      </plot>
   </page>
</product>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/product_6.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE product PUBLIC "-//Tricklab//DTD Product V1.0//EN" "../../XML/DTD/Product.dtd">
<product version="1.0">

<!-- Description: Table with attributes. -->

   <title>Table of Sun Positions</title>
      <table foreground_color="#00ff00" background_color="#556677" >
         <title>Sun Azimuth vs. Time</title>
         <column format="%24.10f">
            <label>Time</label>
            <units>s</units>
            <var>sys.exec.out.time</var>
         </column>
         <column format="%16.5q">
            <label>Azimuth</label>
            <units>d</units>
            <var>sun_predictor.sun.solar_azimuth</var>
         </column>
         <column format="%24.10f">
            <label>Hours</label>
            <units>hr</units>
            <var>sys.exec.out.time</var>
         </column>
         <column format="%24.10f">
            <label>Hours</label>
            <units>hr</units>
            <var units="hr">sys.exec.out.time</var>
         </column>
         <column format="%16.5f">
            <label>Elevation</label>
            <units>d</units>
            <var>sun_predictor.sun.solar_elevation</var>
         </column>
      </table>
</product>
