=== shimpeif/carSim/trick/trick_source/data_products/DPX/XML/DTD/Session.dtd
<!-- Trick DP Session definition -->
<!-- V 1.0 -->

<!ELEMENT tstart        (#PCDATA)>
<!ELEMENT tstop         (#PCDATA)>
<!ELEMENT frequency     (#PCDATA)>
<!ELEMENT file          (#PCDATA)>
<!ELEMENT dir           (#PCDATA)>
<!ELEMENT timename      (#PCDATA)>
<!ELEMENT run           (dir)>
<!ELEMENT product_files (file+)>
<!ELEMENT session       ((tstart|tstop|frequency)*, run+, product_files)>

<!ATTLIST run timename              CDATA #IMPLIED>

<!ATTLIST session version           CDATA #REQUIRED>

<!-- session@presentation attribute
     
     "simple"     - One curve per plot. #plots = #runs x #plot_specifications
     "comparsion" - Multiple runs per plot. 
     "delta"      - difference of two runs.
     "contrast"   - some wierd thing Danny dreamed up.
-->
<!ATTLIST session presentation      CDATA #REQUIRED>

<!-- session@mode attribute
     Indicates a restriction on what in a DP file.

     "plot"   - means that only the plots described in a DP file may be created.
     "table"  - means that only tables described in a DP file may be created.
      default - all plots and tables in the DP may be created.
-->
<!ATTLIST session mode              CDATA #IMPLIED>

<!ATTLIST session device            CDATA #IMPLIED>
<!ATTLIST session gnuplot_terminal  CDATA #IMPLIED>
<!ATTLIST session machine           CDATA #IMPLIED>
<!ATTLIST session port              CDATA #IMPLIED>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/test/TEST_DATA/session_mat.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<!-- This is an XML comment -->
<session version="1.0" presentation="simple">
    <tstart>0.0</tstart>
    <tstop>86400</tstop>
    <frequency>50.0</frequency>
    <run timename="s_simtime">
        <dir>../TEST_DATA/RUN_MATLAB</dir>
    </run>
    <product_files>
        <file>product_mat.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/test/TEST_DATA/session_4_2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<session version="1.0" presentation="DELTA">
    <tstart>0.0</tstart>
    <tstop>86400.0</tstop>
    <frequency>50.0</frequency>
    <run>
        <dir>../TEST_DATA/RUN_BINARY</dir>
    </run>
    <run>
    	<dir>../TEST_DATA/RUN_ASCII</dir>
    </run>
    <product_files>
        <file>product_4.xml</file>
    </product_files>
</session>
