=== shimpeif/carSim/trick/trick_source/data_products/DPX/XML/DTD/Session.dtd
<!-- Trick DP Session definition -->
<!-- V 1.0 -->

<!ELEMENT tstart        (#PCDATA)>
<!ELEMENT tstop         (#PCDATA)>
<!ELEMENT frequency     (#PCDATA)>
<!ELEMENT file          (#PCDATA)>
<!ELEMENT dir           (#PCDATA)>
<!ELEMENT timename      (#PCDATA)>
<!ELEMENT run           (dir)>
<!ELEMENT product_files (file+)>
<!ELEMENT session       ((tstart|tstop|frequency)*, run+, product_files)>

<!ATTLIST run timename              CDATA #IMPLIED>

<!ATTLIST session version           CDATA #REQUIRED>

<!-- session@presentation attribute
     
     "simple"     - One curve per plot. #plots = #runs x #plot_specifications
     "comparsion" - Multiple runs per plot. 
     "delta"      - difference of two runs.
     "contrast"   - some wierd thing Danny dreamed up.
-->
<!ATTLIST session presentation      CDATA #REQUIRED>

<!-- session@mode attribute
     Indicates a restriction on what in a DP file.

     "plot"   - means that only the plots described in a DP file may be created.
     "table"  - means that only tables described in a DP file may be created.
      default - all plots and tables in the DP may be created.
-->
<!ATTLIST session mode              CDATA #IMPLIED>

<!ATTLIST session device            CDATA #IMPLIED>
<!ATTLIST session gnuplot_terminal  CDATA #IMPLIED>
<!ATTLIST session machine           CDATA #IMPLIED>
<!ATTLIST session port              CDATA #IMPLIED>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/session_invDTD.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "Session.dtd">

<!-- This is an XML comment -->

<session version="1.0" presentation="simple" hcells="6" vcells="3">
    <tstart>0</tstart>
    <tstop>86400</tstop>
    <frequency>50.0</frequency>
    <run><dir>BUNCHORUNS/RUN1</dir></run>
    <run><dir>BUNCHORUNS/RUN2</dir></run>
    <run><dir>BUNCHORUNS/RUN3</dir></run>
    <run><dir>BUNCHORUNS/RUN4</dir></run>
    <run><dir>BUNCHORUNS/RUN5</dir></run>
    <product_files>
        <file>product_9.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/TESTING/TEST_DATA/session_4_2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "Session.dtd">
<!-- This is an XML comment -->
<session version="1.0" presentation="DELTA">
    <tstart>0.0</tstart>
    <tstop>86400.0</tstop>
    <frequency>50.0</frequency>
    <runs>
        <dir>RUN1</dir>
        <dir>RUN2</dir>
    </runs>
    <product_files>
        <file>product_4.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/session_testview.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<session version="1.0" presentation="SIMPLE">
	<tstart>0</tstart>
   	<tstop>1000.0</tstop>
    <frequency>100.0</frequency>
    <run timename="this.is.a.time.variable">
    	<dir>../TEST_DATA/RUN_BINARY</dir>
    </run>
    <product_files>
    	<file>product_testview.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/session_8_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<session version="1.0" presentation="SIMPLE" mode="table">
    <tstart>500.0</tstart>
    <tstop>80000.0</tstop>
    <frequency>50.0</frequency>
    <run>
        <dir>../TEST_DATA/RUN_ASCII</dir>
    </run>
    <product_files>
        <file>product_8.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick_source/data_products/DPX/test/TEST_DATA/session_8_1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<session version="1.0" presentation="SIMPLE">
    <tstart>500.0</tstart>
    <tstop>80000.0</tstop>
    <frequency>50.0</frequency>
    <run>
        <dir>../TEST_DATA/RUN_BINARY</dir>
    </run>
    <product_files>
        <file>product_8.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/test/TEST_DATA/session_1_2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<session version="1.0" presentation="stream" machine="chainsaw" port="7000">
    <tstart>0.0</tstart>
    <tstop>86400.0</tstop>
    <frequency>50.0</frequency>
    <run>
        <dir>../TEST_DATA/RUN_ASCII</dir>
    </run>
    <product_files>
        <file>product_1.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick_source/data_products/DPX/TESTING/TEST_DATA/session_3_1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "Session.dtd">
<!-- This is an XML comment -->
<session version="1.0" presentation="SIMPLE">
    <tstart>0.0</tstart>
    <tstop>86400</tstop>
    <frequency>50.0</frequency>
    <run>
        <dir>RUN2</dir>
    </run>
    <product_files>
        <file>product_3.xml</file>
    </product_files>
</session>

=== shimpeif/carSim/trick/trick_source/data_products/DPX/test/TEST_DATA/session_9_1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE session  PUBLIC "-//Tricklab//DTD Session V1.0//EN" "../../XML/DTD/Session.dtd">
<session version="1.0" presentation="comparison">
    <tstart>0</tstart>
    <tstop>86400</tstop>
    <frequency>50.0</frequency>
    <run> <dir>../TEST_DATA/BUNCHORUNS/RUN5</dir> </run>
    <run> <dir>../TEST_DATA/BUNCHORUNS/RUN6</dir> </run>
    <product_files>
        <file>product_9.xml</file>
    </product_files>
</session>
